#pragma once

#include "stdafx.h"

struct SacdDlnaStatus {
    bool broadcasting = false;
    bool httpReady = false;
    bool ssdpReady = false;
    bool httpSelfTestOk = false;
    bool ssdpProbeOk = false;
    bool ssdpNotifyLoopbackOk = false;
    bool networkPresence = false;
    bool remoteHttpSeen = false;
    bool remoteSsdpSeen = false;
    bool sacdInstalled = false;
    bool sharingLibrary = false;
    bool streamingActive = false;
    bool sdxDetected = false;
    bool sdxStreaming = false;
    bool sdxProtocolNegotiated = false;
    bool stabilityMode = true;
    bool conversionActive = false;
    bool networkLogging = false;
    bool dsdProcessorInstalled = false;
    bool dsdProcessorEnabled = false;
    size_t sharedCount = 0;
    uint32_t activeStreams = 0;
    uint16_t port = 8192;
    uint64_t bytesPerSecond = 0;
    uint64_t totalBytesSent = 0;
    uint64_t streamElapsedMs = 0;
    uint64_t cacheBytes = 0;
    uint64_t streamBytesSent = 0;
    uint64_t cacheHits = 0;
    uint64_t cacheMisses = 0;
    uint32_t dsdRate = 0;
    uint64_t nominalBitrate = 0;
    uint64_t requiredBytesPerSecond = 0;
    uint64_t sourceFileSize = 0;
    uint64_t outputFileSize = 0;
    uint32_t sourceSampleRate = 0;
    uint32_t sourceChannels = 0;
    uint32_t sourceBitsPerSample = 0;
    uint32_t streamChannels = 0;
    uint32_t streamBitsPerSample = 0;
    double streamDuration = 0.0;
    double realtimeMultiplier = 0.0;
    uint64_t prebufferBytes = 0;
    uint64_t prebufferTargetBytes = 0;
    uint32_t conversionPercent = 0;
    double networkHeadroom = 0.0;
    uint32_t updateId = 1;
    uint32_t ssdpAliveSent = 0;
    uint32_t ssdpDiscoverSent = 0;
    uint32_t ssdpMSearchReceived = 0;
    uint32_t ssdpResponsesSent = 0;
    uint32_t ssdpDiscoverResponses = 0;
    uint32_t httpRequests = 0;
    uint32_t remoteHttpRequests = 0;
    uint32_t remoteSsdpSearches = 0;
    pfc::string8 serverName;
    pfc::string8 sacdVersion;
    pfc::string8 dsdProcessorVersion;
    pfc::string8 clientIp;
    pfc::string8 clientName;
    pfc::string8 clientModel;
    pfc::string8 streamTitle;
    pfc::string8 streamArtist;
    pfc::string8 streamAlbum;
    pfc::string8 sourceFormat;
    pfc::string8 outputFormat;
    pfc::string8 pipelineState;
    pfc::string8 conversionState;
    pfc::string8 sdxIp;
    pfc::string8 sdxName;
    pfc::string8 sdxModel;
    pfc::string8 sdxModelNumber;
    pfc::string8 sdxProtocolInfo;
    pfc::string8 lastError;
    pfc::string8 lastHttpRequest;
    pfc::string8 localIp;
    pfc::string8 ssdpLastPeer;
    pfc::string8 networkDiagnostic;
    pfc::string8 networkVisibility;
    pfc::string8 lastRemotePeer;
    pfc::string8 prefetchTitle;
    pfc::string8 prefetchState;
    pfc::string8 bufferState;
};
